name: chinese_postman
description: Dart package to solve the Chinese Postman Problem for undirected, weighted graphs
version: 0.1.0
homepage: https://github.com/MadSimple/ChinesePostman

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {dijkstra: ^0.0.2}
